language: php
sudo: required
# dist: trusty
php:
  - 5.4
  # - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=false
  - LIBSODIUM=1.0.1 LIBSODIUMPHP=0.1.3 #(depreciated version without namespaces)
  # - LIBSODIUM=1.0.0 LIBSODIUMPHP=stable
  - LIBSODIUM=stable LIBSODIUMPHP=stable
  - LIBSODIUM=1.0.10 LIBSODIUMPHP=stable
  - LIBSODIUM=nightly LIBSODIUMPHP=stable
before_script:
  - scripts/verifySignature.sh
  - scripts/buildLibsodium.sh
  - scripts/buildLibsodiumPhp.sh

script:
  - scripts/checkLibsodium.sh
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

addons:
  apt:
    # Use more recent version of git, which supports commit/tag verification
    sources:
    - sourceline: 'ppa:git-core/ppa'
    packages:
    - git

matrix:
  exclude:
  # HHVM cannot install PECL extensions and is therefore not compatible
  # with libsodium
  - php: hhvm
  # libsodium-php <0.2.0 is not compatible with PHPv7
  - php: 7.0
    env: LIBSODIUM=1.0.1 LIBSODIUMPHP=0.1.3
  - php: nightly
    env: LIBSODIUM=1.0.1 LIBSODIUMPHP=0.1.3
  # do not run so much tests for nightlies
  - env: LIBSODIUM=nightly LIBSODIUMPHP=stable
    php: 5.4
  - env: LIBSODIUM=nightly LIBSODIUMPHP=stable
    php: 5.5
  - env: LIBSODIUM=nightly LIBSODIUMPHP=stable
    php: 5.6
  - php: nightly
    env: LIBSODIUM=1.0.10 LIBSODIUMPHP=stable
  include:
  - php: hhvm
    env: LIBSODIUM=false
  allow_failures:
  - php: nightly
  - env: LIBSODIUM=nightly LIBSODIUMPHP=stable

notifications:
  email:
    on_success: change
    on_failure: change

